# 后端配置（Git Gateway）
backend:
  name: git-gateway
  branch: main

# 媒体文件存储配置（和 backend 同级）
media_folder: "source/images"
public_folder: "/images"

# 内容集合配置（和 backend 同级）
collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}